[package]
name = "haunted-house"
version = "0.1.0"
edition = "2021"

[lib]
name = "haunted_house"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postcard = { version = "1.0.2", features = ["alloc"] }

anyhow = "1"
uuid = { version = "*", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
tempfile = "3"
log = "*"
env_logger = "0.9"
bitvec = "*"
hex = "*"


tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
async-trait = "0.1"
sha2 = "*"
itertools = "*"

poem = { version = "1.3", features = ["anyhow"] }

sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite" ] }
#deadpool-sqlite = "0.5"

pyo3 = { version = "0.17", features = ["extension-module", "anyhow", "chrono"] }
pyo3-asyncio = { version = "0.17", features = ["attributes", "tokio-runtime"] }
pyo3-log = { version = "0.7" }

[dev-dependencies]
rand = "*"
assertor = "*"