[package]
name = "haunted-house"
version = "0.1.0"
edition = "2021"

#[[bin]]
#name = "worker"
#test = false
#bench = false
#path = "src/worker.rs"

[lib]
name = "haunted_house"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
postcard = { version = "1.0.2", features = ["alloc"] }
bytes = "*"

anyhow = "1"
uuid = { version = "*", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
parse_duration = "2"
tempfile = "3"
log = "*"
env_logger = "0.9"
bitvec = "*"
hex = "*"
sha2 = "*"
itertools = "*"
weak-self = "*"
gethostname = "0.4"
yara = { version = "0.16", features= ["vendored"] }


tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"
async-trait = "0.1"

poem = { version = "1.3", features = ["anyhow"] }
reqwest = { version = "0.11", features = ["json"] }

sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite" ] }

pyo3 = { version = "0.17", features = ["anyhow", "chrono"] }
pyo3-asyncio = { version = "0.17", features = ["attributes", "tokio-runtime"] }
pyo3-log = { version = "0.7" }

azure_core = "0.7"
azure_storage = "0.8"
azure_storage_blobs = "0.8"

[dev-dependencies]
rand = "*"
assertor = "*"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]