
version: "2.4"

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: al_storage_key
      MINIO_ROOT_PASSWORD: Ch@ngeTh!sPa33w0rd
    ports:
      - "9000:9000"
    command: server /data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000

  mysql:
    image: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    # command: --binlog-expire-logs-seconds=86400
    command: --binlog-expire-logs-seconds=3600
    environment:
      MYSQL_DATABASE: haunted
      MYSQL_USER: haunted
      MYSQL_PASSWORD: d4941d0d8bf64e1b64fb
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "./test-data/mysql:/var/lib/mysql"